name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2.2.1
    - name: Check Rustfmt
      run: cargo fmt -- --check
    - name: Check Clippy
      run: cargo clippy

  build:
    needs: [lint]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2.2.1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
