name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latest stable
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2.7.3
    - name: Check Rustfmt
      run: cargo fmt -- --check
    - name: Check Clippy
      run: cargo clippy

  build:
    needs: [lint]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latest stable
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2.7.3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
